"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  fetchProductCategories,
  bulkCreateProductCategories,
} from "@/app/api/productCategoryApi";

const SAMPLE = `Electronics
  Mobile Phones
  Laptops
  Headphones
Home & Kitchen
  Cookware
  Small Appliances`;

function parseTree(text) {
  const groups = [];
  const problems = [];

  text.split("\n").forEach((raw, i) => {
    if (!raw.trim()) return;
    const isChild = /^[\s\-*•]/.test(raw);
    const name = raw.replace(/^[\s\-*•]+/, "").trim();
    if (!name) return;

    if (!isChild) {
      groups.push({ name, children: [] });
      return;
    }
    if (!groups.length) {
      problems.push(`Line ${i + 1}: "${name}" has no parent above it`);
      return;
    }
    groups[groups.length - 1].children.push({ name });
  });

  return { groups, problems };
}

export default function BulkProductCategoryPage() {
  const [text, setText] = useState("");
  const [existing, setExisting] = useState([]);
  const [loadError, setLoadError] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);

  const loadExisting = async () => {
    try {
      const tree = await fetchProductCategories({ includeInactive: true });
      setExisting(tree);
      setLoadError(null);
    } catch (err) {
      setLoadError(err.message);
    }
  };

  useEffect(() => {
    // setState happens only after an await inside loadCategories — not synchronous.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    loadExisting();
  }, []);

  const existingByName = useMemo(() => {
    const map = new Map();
    existing.forEach((r) => map.set(r.name.trim().toLowerCase(), r));
    return map;
  }, [existing]);

  const { groups, problems } = useMemo(() => parseTree(text), [text]);

  const plan = useMemo(
    () =>
      groups.map((g) => {
        const match = existingByName.get(g.name.trim().toLowerCase());
        return { ...g, existingCode: match ? match.code : null };
      }),
    [groups, existingByName],
  );

  const totalNew = plan.reduce(
    (acc, g) => acc + (g.existingCode ? 0 : 1) + g.children.length,
    0,
  );

  const buildPayload = () => {
    const payload = [];
    plan.forEach((g) => {
      if (g.existingCode) {
        g.children.forEach((c) =>
          payload.push({ name: c.name, parentCode: g.existingCode }),
        );
      } else {
        payload.push({ name: g.name, children: g.children });
      }
    });
    return payload;
  };

  const submit = async () => {
    setError(null);
    setResult(null);
    setSubmitting(true);
    try {
      const data = await bulkCreateProductCategories(buildPayload());
      setResult(data);
      await loadExisting();
    } catch (err) {
      setError(err.message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F5F6F8]">
      <div className="mx-auto max-w-4xl px-6 py-8">
        <Link
          href="/product-category"
          className="text-sm text-[#6B7280] hover:underline"
        >
          ← Back to product categories
        </Link>

        <header className="mt-4 mb-6">
          <h1 className="text-xl font-semibold text-[#1B1F27]">
            Bulk create product categories
          </h1>
          <p className="text-sm text-[#6B7280] mt-1">
            One category per line. Indent (or prefix with “-”) to make a
            subcategory of the line above. Codes are generated by the backend;
            rules default to the standard fee schedule and can be edited after.
          </p>
        </header>

        {loadError && (
          <p className="mb-4 rounded-md border border-[#FDA29B] bg-[#FEF3F2] px-3 py-2 text-sm text-[#B42318]">
            {loadError}
          </p>
        )}

        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-xl border border-[#E4E7EC] bg-white p-4">
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-semibold uppercase tracking-wide text-[#6B7280]">
                Categories
              </label>
              <button
                type="button"
                onClick={() => setText(SAMPLE)}
                className="text-xs font-semibold text-[#2F5D9F] hover:text-[#1F3F73]"
              >
                Insert example
              </button>
            </div>
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              rows={18}
              spellCheck={false}
              placeholder={SAMPLE}
              className="w-full resize-y rounded-md border border-[#D0D5DD] px-3 py-2 font-mono text-sm leading-6 focus:outline-none focus:ring-2 focus:ring-[#2F5D9F]/40 focus:border-[#2F5D9F]"
            />
          </div>

          <div className="rounded-xl border border-[#E4E7EC] bg-white p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#6B7280] mb-2">
              Preview — {totalNew} to create
            </p>

            {problems.map((p) => (
              <p key={p} className="text-xs text-[#B42318] mb-1">
                {p}
              </p>
            ))}

            {plan.length === 0 && (
              <p className="text-sm text-[#6B7280] py-6 text-center">
                Nothing to create yet.
              </p>
            )}

            <div className="max-h-[420px] overflow-y-auto">
              {plan.map((g, i) => (
                <div key={`${g.name}-${i}`} className="py-1.5">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-[#1B1F27]">
                      {g.name}
                    </span>
                    {g.existingCode ? (
                      <span className="rounded-full bg-[#F2F4F7] px-2 py-0.5 text-[10px] font-semibold text-[#6B7280]">
                        exists · {g.existingCode}
                      </span>
                    ) : (
                      <span className="rounded-full bg-[#DCFCE7] px-2 py-0.5 text-[10px] font-semibold text-[#15803D]">
                        new root
                      </span>
                    )}
                  </div>
                  {g.children.map((c, j) => (
                    <div
                      key={`${c.name}-${j}`}
                      className="flex items-center gap-2 pl-6 py-0.5"
                    >
                      <span className="text-[#D0D5DD]">↳</span>
                      <span className="text-sm text-[#374151]">{c.name}</span>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        </div>

        {error && (
          <p className="mt-4 rounded-md border border-[#FDA29B] bg-[#FEF3F2] px-3 py-2 text-sm text-[#B42318]">
            {error}
          </p>
        )}

        {result && (
          <div className="mt-4 rounded-xl border border-[#E4E7EC] bg-white p-4">
            <p className="text-sm font-semibold text-[#1B1F27] mb-2">
              Created {result.results.length} · Failed {result.errors.length}
            </p>
            <div className="max-h-56 overflow-y-auto space-y-1">
              {result.results.map((r) => (
                <p key={r.code} className="text-xs text-[#15803D]">
                  <span className="font-mono">{r.code}</span> · {r.name}
                </p>
              ))}
              {result.errors.map((e, i) => (
                <p key={`${e.name}-${i}`} className="text-xs text-[#B42318]">
                  {e.name}: {e.error}
                </p>
              ))}
            </div>
          </div>
        )}

        <div className="mt-4 flex items-center gap-3">
          <button
            type="button"
            onClick={submit}
            disabled={submitting || totalNew === 0}
            className="rounded-md bg-[#2F5D9F] px-4 py-2 text-sm font-semibold text-white hover:bg-[#1F3F73] disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {submitting ? "Creating…" : `Create ${totalNew} categories`}
          </button>
          <button
            type="button"
            onClick={() => {
              setText("");
              setResult(null);
              setError(null);
            }}
            disabled={submitting}
            className="rounded-md px-4 py-2 text-sm font-medium text-[#374151] hover:bg-white"
          >
            Clear
          </button>
        </div>
      </div>
    </div>
  );
}
